name: release chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/hajimari/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Initialize chart repository
        run: |
          if ! git ls-remote --exit-code --heads origin gh-pages \
            >/dev/null; then
            empty_tree=$(git mktree </dev/null)
            commit=$(git commit-tree "$empty_tree" \
              -m "Initialize chart repository")
            git push origin "$commit:refs/heads/gh-pages"
          fi
          git fetch origin gh-pages:refs/remotes/origin/gh-pages

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.6.3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
          CR_RELEASE_NAME_TEMPLATE: "hajimari-helm-chart-{{ .Version }}"
